### ISSUE TITLE
Enhancement Idea

### ISSUE THREAD

**Issue by petty** [skelato1/obsidian-auto-hide#15]
I've added the following Custom CSS snippet:

```css
@media (min-width: 1600px) {
    .mod-left-split.is-sidedock-collapsed {
        width: auto !important;
        display: flex !important;
        min-width: 320px;
    }
}
@media (min-width: 2400px) {
     .is-sidedock-collapsed {
        width: auto !important;
        display: flex !important;
        min-width: 320px;
    }
}
```

That CSS forces the "auto hidden" sidebars to be displayed at certain window sizes, which means when I drag or open Obsidian on a big external display I can see everything but on a smaller laptop screen with a smaller window size the Auto Hide functionality works as designed.

This could be a cool Setting (where maybe you could override or input the screen size you'd want to force things open at ...

I was using the Pin feature, and this is similar but no clicking required to Pin / un-Pin.

Auto Hide is a great plugin for Obsidian.
